# Try to autogenerate the nix file generated by cabal2nix.  This enables a
# haskell project to be described solely by its cabal file and its source
# folder.
# 'cabalFile' is a string naming a file residing in the 'src' folder.
{ stdenv, glibcLocales, cabal2nix} : src : cabalFile :
  stdenv.mkDerivation {

    name = "nix-gen-cabal";
    buildInputs = [ cabal2nix ];

    # cabal2nix (and haskell programs in general..) need a UTF local set to
    # function properly.
    LANG = "en_US.UTF-8";
    LOCALE_ARCHIVE = stdenv.lib.optionalString stdenv.isLinux
      "${glibcLocales}/lib/locale/locale-archive";

    builder = builtins.toFile "builder.sh" ''
      source $stdenv/setup
      cabal2nix --sha256=0 ${src}/${cabalFile} > $out
      set -o verbose

      # "Oh the horror"-hack. Works incidentally...
      sed -e "s;sha256.*$;src = ${src}\;\n  doCheck = true\;;" -i $out
    '';

    inherit src cabalFile;
  }
